# Generated by Django 4.2.6 on 2023-10-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='body',
        ),
    ]
