# Generated by Django 4.2.6 on 2023-11-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.houseunits')),
            ],
        ),
    ]
