# Generated by Django 4.2.6 on 2023-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_houserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserequest',
            name='requested',
            field=models.BooleanField(null=True),
        ),
    ]
