# Generated by Django 4.2.6 on 2023-11-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_houserequest_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houserequest',
            old_name='tenant',
            new_name='user',
        ),
    ]
